### ISSUE TITLE
Fix automated release / tagging

### ISSUE THREAD

**Issue by joshjohanning** [stefanbuck/github-issue-parser#48]
See: https://github.com/stefanbuck/github-issue-parser/pull/47#issuecomment-1286189244

> For some odd reason the release pipeline was using an older commit as a baseline and this resulted in another 3.0.0 release ergo the pipeline failed with `tag 'v3.0.0' already exists`. I created the release manual for now, but the same happened earlier before as well see [#43 (comment)](https://github.com/stefanbuck/github-issue-parser/pull/43#issuecomment-1283287852) @gr2m do you have any idea what is causing this?
> 
> Given this is happening since #39 it must be related to this change. Is there another way to address #23?

cc @stefanbuck @gr2m

**Comment by evverx** [comment]
Looking at https://github.com/systemd/systemd/pull/25900#issuecomment-2028912672 I wonder if the code was force-pushed and the history was overwritten at some point?

**Comment by gr2m** [comment]
Tags or commits currently cannot be used directly because they lack the `dist/` folder, e.g. https://github.com/stefanbuck/github-issue-parser/tree/v3.2.0 

I suggest we copy the setup of https://github.com/actions/create-github-app-token, where the `dist/` folder is updated automatically as part of the release directly in the default branch. Repository rules now allow branch protections to be circumvented for actors, so we can register a single purpose GitHub App for this task, in order to keep branch protections in tact as they are

**Comment by gr2m** [comment]
See also https://github.com/stefanbuck/github-issue-parser/issues/74

**Comment by jamacku** [comment]
Also #82

**Comment by stefanbuck** [comment]
Thank you all for your patience and for continuing to report this issue. It's long overdue for a fix, and I plan to address it over the holiday break.

**Comment by gr2m** [comment]
Holler if you run into any blockers. I'm sorry I couldn't look into it myself
